on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Verify commit exists in origin/master
      run: git branch --remote --contains | grep origin/master
    - name: Extract release notes
      run: |
        git log --pretty=format:'%d %s' ${GITHUB_REF} | perl -pe 's| \(.*tag: v(\d+.\d+.\d+(-preview\d{3})?)(, .*?)*\)|\n## \1\n|g' > RELEASE-NOTES
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Build
      run: dotnet build "_src\IMetadataAware.Core.sln" --configuration Release /p:Version=${VERSION}
    - name: Publish Zoka.IMetadataAware.Core nuget to nuget.org
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: _src/IMetadataAware.Core/IMetadataAware.Core.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_STATIC: $VERSION